/**
 * InvoiceMetadataV1 — canonical schema for invoice NFT metadata uploaded to IPFS.
 *
 * Conforms to the OpenSea / ERC-1155 metadata standard extended with
 * invoice-specific fields. All metadata uploaded via lib/ipfs.ts must
 * pass this schema before being pinned.
 *
 * Version: 1.0
 * Closes #121
 */

import { z } from "zod";
import { env } from "@/lib/env";
import { isValidCID } from "./ipfs";

// ─── Constants ────────────────────────────────────────────────────────────────

export const METADATA_VERSION = "1.0" as const;

export const SUPPORTED_CURRENCIES = ["USDC", "EURC", "XLM"] as const;

export const SUPPORTED_JURISDICTIONS = [
  "US", "EU", "UK", "NG", "KE", "GH", "ZA", "OTHER",
] as const;

export const SUPPORTED_CATEGORIES = [
  "technology",
  "manufacturing",
  "logistics",
  "healthcare",
  "retail",
  "construction",
  "agriculture",
  "energy",
  "finance",
  "other",
] as const;

export const SUPPORTED_RISK_TIERS = [
  "AAA", "AA", "A", "BBB", "BB", "B", "CCC",
] as const;

// ─── InvoiceMetadataV1 Zod Schema ─────────────────────────────────────────────

/**
 * Full schema for invoice NFT metadata (version 1.0).
 *
 * Required fields follow the NFT metadata standard (name, description, image)
 * plus the invoice-specific fields needed for on-chain verification.
 *
 * Optional fields provide richer context for marketplace display and
 * risk assessment without breaking backward compatibility.
 */
export const invoiceMetadataV1Schema = z.object({
  // ── Versioning ──────────────────────────────────────────────────────────────
  /** Schema version — always "1.0" for this schema. Used for future migrations. */
  metadata_version: z.literal(METADATA_VERSION),

  // ── NFT Standard Fields (required) ─────────────────────────────────────────
  /** Human-readable name for the NFT (e.g. "Invoice INV-2024-0001"). */
  name: z.string().min(1, "name is required").max(256),

  /** Human-readable description of the invoice asset. */
  description: z.string().min(1, "description is required").max(2048),

  /**
   * URI of the NFT image — either an IPFS URI (ipfs://CID) or an
   * HTTPS gateway URL. This is the SVG invoice preview generated by
   * generateInvoiceSvg().
   */
  image: z
    .string()
    .min(1, "image is required")
    .refine(
      (v) => v.startsWith("ipfs://") || v.startsWith("https://"),
      "image must be an ipfs:// or https:// URI"
    ),

  // ── Invoice Identity (required) ─────────────────────────────────────────────
  /** Unique invoice identifier (e.g. "INV-2024-0001"). */
  invoice_number: z
    .string()
    .min(1, "invoice_number is required")
    .regex(/^[a-zA-Z0-9-]+$/, "invoice_number must be alphanumeric with hyphens"),

  /** Invoice face value in the smallest representable unit (e.g. USDC cents). */
  amount: z.number().positive("amount must be positive"),

  /** Currency code. */
  currency: z.enum(SUPPORTED_CURRENCIES),

  /**
   * ISO 8601 date string for when the invoice is due (e.g. "2025-03-01").
   * Used by the smart contract to enforce repayment deadlines.
   */
  due_date: z
    .string()
    .min(1, "due_date is required")
    .regex(/^\d{4}-\d{2}-\d{2}$/, "due_date must be YYYY-MM-DD"),

  // ── Parties (required) ──────────────────────────────────────────────────────
  /**
   * Issuer information — the SME that created the invoice.
   * Contains at minimum the wallet address; display name is optional.
   */
  issuer: z.object({
    /** Stellar public key of the issuer (G...). */
    address: z
      .string()
      .min(1, "issuer.address is required")
      .regex(/^G[A-Z2-7]{55}$/, "issuer.address must be a valid Stellar public key"),
    /** Human-readable display name (company name). */
    name: z.string().max(256).optional(),
  }),

  /**
   * Debtor information — the entity that owes the invoice amount.
   * May be partially or fully anonymized depending on privacy settings.
   */
  debtor: z.object({
    /** Display name or anonymized label (e.g. "Technology Company, Kenya"). */
    name: z.string().min(1, "debtor.name is required").max(256),
    /** Physical or registered address. Omitted when privacy = anonymized. */
    address: z.string().max(512).optional(),
    /** Privacy level applied to this debtor's information. */
    privacy: z.enum(["full", "partial", "anonymized"]).default("full"),
  }),

  // ── Optional Enrichment Fields ──────────────────────────────────────────────
  /** ISO 3166-1 alpha-2 country code or region code (e.g. "KE", "EU"). */
  jurisdiction: z.enum(SUPPORTED_JURISDICTIONS).optional(),

  /** Industry category of the invoice. */
  category: z.enum(SUPPORTED_CATEGORIES).optional(),

  /** Risk tier assigned by the protocol's risk engine. */
  risk_tier: z.enum(SUPPORTED_RISK_TIERS).optional(),

  /**
   * Discount rate as a decimal (e.g. 0.05 = 5%).
   * Represents the yield offered to investors.
   */
  discount_rate: z
    .number()
    .min(0, "discount_rate must be >= 0")
    .max(1, "discount_rate must be <= 1 (100%)")
    .optional(),

  /**
   * IPFS CID of the original invoice PDF document.
   * Allows anyone to verify the underlying document.
   */
  ipfs_document_cid: z
    .string()
    .regex(
      /^(Qm[1-9A-HJ-NP-Za-km-z]{44}|bafy[a-z2-7]{52,})$/,
      "ipfs_document_cid must be a valid IPFS CID (v0 or v1)"
    )
    .optional(),

  /**
   * External URL for the NFT — typically the marketplace listing page.
   * Displayed by NFT explorers as a "View on Kora" link.
   */
  external_url: z
    .string()
    .url("external_url must be a valid URL")
    .optional(),

  /**
   * Structured attributes array following the OpenSea metadata standard.
   * Enables trait-based filtering in NFT marketplaces.
   */
  attributes: z
    .array(
      z.object({
        trait_type: z.string().min(1),
        value: z.union([z.string(), z.number()]),
        display_type: z
          .enum(["number", "boost_number", "boost_percentage", "date"])
          .optional(),
      })
    )
    .optional(),
});

// ─── Derived Types ────────────────────────────────────────────────────────────

export type InvoiceMetadataV1 = z.infer<typeof invoiceMetadataV1Schema>;

/** Input type before version field is added (used by builders). */
export type InvoiceMetadataV1Input = Omit<InvoiceMetadataV1, "metadata_version">;

let purifyInstance: any = null;
function getPurify() {
  if (typeof window !== "undefined") {
    // eslint-disable-next-line
    return require("dompurify");
  }
  if (!purifyInstance) {
    try {
      // eslint-disable-next-line no-eval
      const jsdom = eval("require")("jsdom");
      // eslint-disable-next-line no-eval
      const dompurify = eval("require")("dompurify");
      const { window } = new jsdom.JSDOM("");
      purifyInstance = dompurify(window);
    } catch (e) {
      return {
        sanitize: (text: string) => text.replace(/<[^>]*>/g, ""),
      };
    }
  }
  return purifyInstance;
}

export function sanitizeText(text: string): string {
  if (!text) return "";
  const purify = getPurify();
  return purify.sanitize(text, { ALLOWED_TAGS: [], ALLOWED_ATTR: [] });
}

export function sanitizeInvoiceMetadata(metadata: InvoiceMetadataV1): InvoiceMetadataV1 {
  const sanitized = { ...metadata };
  sanitized.name = sanitizeText(metadata.name);
  sanitized.description = sanitizeText(metadata.description);

  if (metadata.issuer) {
    sanitized.issuer = {
      ...metadata.issuer,
      name: metadata.issuer.name ? sanitizeText(metadata.issuer.name) : undefined,
    };
  }

  if (metadata.debtor) {
    sanitized.debtor = {
      ...metadata.debtor,
      name: sanitizeText(metadata.debtor.name),
      address: metadata.debtor.address ? sanitizeText(metadata.debtor.address) : undefined,
    };
  }

  if (metadata.attributes) {
    sanitized.attributes = metadata.attributes.map((attr) => ({
      ...attr,
      trait_type: sanitizeText(attr.trait_type),
      value: typeof attr.value === "string" ? sanitizeText(attr.value) : attr.value,
    }));
  }

  return sanitized;
}

/**
 * Validate raw metadata against the InvoiceMetadataV1 schema.
 *
 * Returns a typed result object — never throws.
 *
 * @example
 * const result = validateInvoiceMetadata(raw);
 * if (!result.success) {
 *   console.error(result.errors);
 * }
 */
export function validateInvoiceMetadata(
  raw: unknown
): { success: true; data: InvoiceMetadataV1 } | { success: false; errors: string[] } {
  const result = invoiceMetadataV1Schema.safeParse(raw);
  if (result.success) {
    return { success: true, data: sanitizeInvoiceMetadata(result.data) };
  }
  const errors = result.error.issues.map(
    (issue) => `${issue.path.join(".")}: ${issue.message}`
  );
  return { success: false, errors };
}

function canonicalizeMetadata(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map(canonicalizeMetadata).join(",")}]`;
  }
  if (value && typeof value === "object" && !(value instanceof Date)) {
    const sortedKeys = Object.keys(value as Record<string, unknown>).sort();
    return `{${sortedKeys
      .map((key) => `${JSON.stringify(key)}:${canonicalizeMetadata((value as Record<string, unknown>)[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

export async function verifyMetadataIntegrity(
  cid: string,
  metadata: unknown
): Promise<boolean> {
  if (env.NEXT_PUBLIC_ENABLE_MOCK_DATA) {
    return true;
  }
  if (!cid || typeof cid !== "string" || !isValidCID(cid)) {
    return false;
  }
  try {
    const gateway = env.NEXT_PUBLIC_IPFS_GATEWAY || "https://ipfs.io";
    const response = await fetch(`${gateway}/${cid}`, { cache: "no-store" });
    if (!response.ok) {
      return false;
    }
    const remote = await response.json();
    return canonicalizeMetadata(remote) === canonicalizeMetadata(metadata);
  } catch (error) {
    console.warn("Invoice metadata integrity verification failed", error);
    return false;
  }
}

/**
 * Parse and validate metadata, throwing a descriptive error on failure.
 * Use this in upload flows where invalid metadata should abort the operation.
 *
 * @throws {Error} with a human-readable list of validation failures
 */
export function parseInvoiceMetadata(raw: unknown): InvoiceMetadataV1 {
  const result = validateInvoiceMetadata(raw);
  if (!result.success) {
    throw new Error(
      `Invalid invoice metadata (v${METADATA_VERSION}):\n${result.errors.join("\n")}`
    );
  }
  return result.data;
}

// ─── Metadata Builder ─────────────────────────────────────────────────────────

/**
 * Build a validated InvoiceMetadataV1 object from raw invoice form data.
 * Automatically adds the metadata_version field and constructs the
 * attributes array for NFT marketplace compatibility.
 *
 * @param input - Invoice data without the version field
 * @returns Validated InvoiceMetadataV1 object
 * @throws {Error} if the resulting metadata fails schema validation
 */
export function buildInvoiceMetadata(
  input: InvoiceMetadataV1Input
): InvoiceMetadataV1 {
  const raw: InvoiceMetadataV1 = {
    metadata_version: METADATA_VERSION,
    ...input,
    // Auto-generate attributes array if not provided
    attributes: input.attributes ?? buildAttributes(input),
  };
  return parseInvoiceMetadata(raw);
}

/**
 * Build the OpenSea-compatible attributes array from invoice fields.
 * This enables trait-based filtering in NFT marketplaces.
 */
function buildAttributes(
  input: InvoiceMetadataV1Input
): InvoiceMetadataV1["attributes"] {
  const attrs: NonNullable<InvoiceMetadataV1["attributes"]> = [
    { trait_type: "Invoice Number", value: input.invoice_number },
    { trait_type: "Currency", value: input.currency },
    { trait_type: "Amount", value: input.amount, display_type: "number" },
    { trait_type: "Due Date", value: input.due_date },
  ];

  if (input.jurisdiction) {
    attrs.push({ trait_type: "Jurisdiction", value: input.jurisdiction });
  }
  if (input.category) {
    attrs.push({ trait_type: "Category", value: input.category });
  }
  if (input.risk_tier) {
    attrs.push({ trait_type: "Risk Tier", value: input.risk_tier });
  }
  if (input.discount_rate !== undefined) {
    attrs.push({
      trait_type: "Discount Rate",
      value: Math.round(input.discount_rate * 100),
      display_type: "boost_percentage",
    });
  }

  return attrs;
}
